-- 코드를 입력하세요
WITH SALE AS (
    SELECT
        SUM(SALES_AMOUNT) AS AMOUNT
    ,   PRODUCT_ID
    FROM
        OFFLINE_SALE
    GROUP BY
        PRODUCT_ID
)

SELECT
    PRODUCT_CODE
,   AMOUNT * PRICE AS SALES
FROM
    PRODUCT P
,   SALE S
WHERE
    P.PRODUCT_ID = S.PRODUCT_ID
ORDER BY
    SALES DESC
,   PRODUCT_CODE