WITH CCC AS (
    SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        P.DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
            ON C.CAR_TYPE = P.CAR_TYPE
    WHERE
        C.CAR_TYPE IN ('세단', 'SUV')
        AND P.DURATION_TYPE = '30일 이상'
),
CCRH AS (
    SELECT
        DISTINCT CAR_ID
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE <= DATE '2022-11-30'
        AND END_DATE >= DATE '2022-11-01'
)
SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM
    CCC C
LEFT JOIN
    CCRH H ON C.CAR_ID = H.CAR_ID
WHERE
    H.CAR_ID IS NULL
    AND ROUND(C.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30) BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE,
    C.CAR_ID DESC;
