-- 코드를 입력하세요
SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED BETWEEN TO_DATE('2021-01-01', 'YYYY-DD-MM') AND TO_DATE('2021-12-31', 'YYYY-MM-DD')), 1) AS PUCHASED_RATIO
FROM
    ONLINE_SALE O
,   USER_INFO   U
WHERE
        O.USER_ID = U.USER_ID
    AND U.JOINED BETWEEN TO_DATE('2021-01-01', 'YYYY-DD-MM') AND TO_DATE('2021-12-31', 'YYYY-MM-DD')
GROUP BY
    EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY
    YEAR, MONTH