-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, PRODUCT_NAME, (SUM(AMOUNT) * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
LEFT JOIN FOOD_ORDER AS FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE <= '2022-05-31'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC