-- 코드를 입력하세요
SELECT 
P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
LEFT JOIN FOOD_ORDER AS O ON P.PRODUCT_ID = O.PRODUCT_ID

WHERE 
        O.PRODUCE_DATE > '2022-04-30'
    AND O.PRODUCE_DATE < '2022-06-01'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC