WITH FOOD AS (
    SELECT
        PRODUCT_ID
    ,   AMOUNT
    FROM
        FOOD_ORDER
    WHERE
        PRODUCE_DATE BETWEEN
            TO_DATE('2022-05-01', 'YYYY-MM-DD')
        AND TO_DATE('2022-05-31', 'YYYY-MM-DD')
)
SELECT
    FP.PRODUCT_ID
,   FP.PRODUCT_NAME
,   SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT FP
    JOIN
        FOOD F
    ON (FP.PRODUCT_ID = F.PRODUCT_ID)
GROUP BY
    FP.PRODUCT_ID
,   FP.PRODUCT_NAME
ORDER BY
    SUM(PRICE * AMOUNT) DESC
,   PRODUCT_ID ASC