-- 코드를 입력하세요
SELECT
    HISTORY_ID,
    FLOOR(
        (DATEDIFF(END_DATE, START_DATE) + 1) *
        CASE WHEN (DATEDIFF(END_DATE, START_DATE) + 1) < 7 THEN DAILY_FEE
        ELSE DAILY_FEE * (100 - DISCOUNT_RATE) / 100 END
    ) AS FEE
    
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
JOIN
    CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING(CAR_TYPE)
WHERE
    CAR_TYPE LIKE '트럭'
    AND
    DURATION_TYPE LIKE CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상' 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE '7일 이상' END
ORDER BY
    FEE DESC,
    HISTORY_ID DESC