-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE AS M
LEFT JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
WHERE MEMBER_NAME = 
    (
        SELECT MEMBER_NAME 
        FROM MEMBER_PROFILE AS M
        LEFT JOIN REST_REVIEW AS R ON M.MEMBER_ID = R.MEMBER_ID
        GROUP BY M.MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
